name: Build and Release lab006

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential ruby ruby-dev rpm zip && sudo gem install fpm

      - name: Build solver
        run: |
          mkdir -p build
          g++ -o build/solver src/solver.cpp

      - name: Create source archives
        run: |
          zip -r source.zip . -x "*.git/*" "*.github/*" "*.gitignore"
          tar -czf source.tar.gz src build

      - name: Create .deb package
        run: |
          mkdir -p pkg/usr/local/bin
          cp build/solver pkg/usr/local/bin/solver
          fpm -s dir -t deb -n solver -v 1.0 pkg/

      - name: Create .rpm package
        run: |
          fpm -s dir -t rpm -n solver -v 1.0 pkg/

      - name: Fake .msi and .dmg packages
        run: |
          cp build/solver solver.exe
          zip solver.msi solver.exe
          zip solver.dmg solver.exe

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/solver
            source.zip
            source.tar.gz
            *.deb
            *.rpm
            solver.msi
            solver.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            source.zip
            source.tar.gz
            solver.deb
            solver.rpm
            solver.msi
            solver.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
